# Generated by Django 3.0.3 on 2020-03-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0014_auto_20200324_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='image3',
        ),
    ]
