# Generated by Django 2.2.11 on 2020-03-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0016_flightuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightuser',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
