# Generated by Django 2.2.11 on 2020-03-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0021_bookhotel_bookpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='seats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
