# Generated by Django 2.2.11 on 2020-03-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0024_bookflight_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpackage',
            name='seat',
            field=models.IntegerField(default=1),
        ),
    ]
