# Generated by Django 2.2.11 on 2020-03-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0026_bookhotel_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
    ]
